services:
  neon_local:
    # Use major version for production, or specify minor version like ghcr.io/neondatabase-labs/neon_local:v1.2
    # Available tags: latest, v1, v1.2, <short-sha>
    # image: ghcr.io/neondatabase-labs/neon_local:v1
    # Uncomment the line below for local development
    build: app/
    ports:
      - "5432:5432"
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      PARENT_BRANCH_ID: ${PARENT_BRANCH_ID}
      #BRANCH_ID: br-dark-bar-a440iizf
      #DELETE_BRANCH: < True | False >
      #DRIVER: < postgres | serverless >
    #volumes:
    #  - ./.neon_local/:/tmp/.neon_local
    #  - ../.git/HEAD:/tmp/.git/HEAD:ro,consistent